In [152]:

class MyLR:
    
    def __init__(self):
        self.m = None
        self.b = None
        
    def fit(self,X_train,y_train):
        
        num = 0
        den = 0
        
        for i in range(X_train.shape[0]):
            
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
        
        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)       
    
    def predict(self,X_test):
        
        print(X_test)
        
        return self.m * X_test + self.b
    

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn 

In [2]:
df=pd.read_csv('student_data.csv')
df

CGPA  Package (in Lakhs)
0    6.25               13.91
1    9.70                4.43
2    8.39                5.75
3    7.59               18.28
4    4.94               13.31
..    ...                 ...
195  6.10               18.82
196  8.36               17.59
197  9.38               10.29
198  9.32               15.76
199  8.68               15.83

[200 rows x 2 columns]

In [102]:
x = df.iloc[:,0:1].values
y = df.iloc[:,-1].values

In [106]:
x

array([[6.25],
       [9.7 ],
       [8.39],
       [7.59],
       [4.94],
       [4.94],
       [4.35],
       [9.2 ],
       [7.61],
       [8.25],
       [4.12],
       [9.82],
       [8.99],
       [5.27],
       [5.09],
       [5.1 ],
       [5.83],
       [7.15],
       [6.59],
       [5.75],
       [7.67],
       [4.84],
       [5.75],
       [6.2 ],
       [6.74],
       [8.71],
       [5.2 ],
       [7.09],
       [7.55],
       [4.28],
       [7.65],
       [5.02],
       [4.39],
       [9.69],
       [9.79],
       [8.85],
       [5.83],
       [4.59],
       [8.11],
       [6.64],
       [4.73],
       [6.97],
       [4.21],
       [9.46],
       [5.55],
       [7.98],
       [5.87],
       [7.12],
       [7.28],
       [5.11],
       [9.82],
       [8.65],
       [9.64],
       [9.37],
       [7.59],
       [9.53],
       [4.53],
       [5.18],
       [4.27],
       [5.95],
       [6.33],
       [5.63],
       [8.97],
       [6.14],
       [5.69],
       [7.26],
       [4.

In [52]:
y

array([13.91,  4.43,  5.75, 18.28, 13.31,  3.16,  4.73, 14.28,  3.09,
        5.73, 12.33, 14.76, 14.08,  6.81, 15.11,  7.03,  8.53, 15.69,
       14.04, 17.44, 14.18, 12.66,  4.59,  9.25,  7.51,  7.15, 19.54,
        9.68, 18.16, 13.73, 16.51, 11.54, 12.81, 11.37,  6.32, 15.28,
        7.77,  3.41, 13.97,  6.01, 18.99, 19.22, 18.55,  9.29,  3.26,
       18.78, 10.28, 19.43, 19.38, 17.5 ,  8.01,  9.55, 17.47,  8.39,
        5.88, 12.47, 18.91, 14.83, 12.69,  4.65, 13.46, 19.83,  5.38,
       11.81, 17.92, 15.59, 14.85, 14.94,  9.11,  7.99, 16.76, 16.77,
       17.74, 18.53, 11.69, 11.53, 16.57, 14.05, 14.93, 16.53, 18.13,
        8.75,  9.38,  4.6 , 12.83,  3.61, 10.92, 12.22,  7.87, 13.04,
        3.52,  3.63, 16.98,  9.12,  5.16, 11.88, 16.09,  6.67, 13.59,
        4.45,  3.88, 12.03, 12.19, 13.84, 15.34, 19.59, 11.78,  8.49,
       16.52,  7.6 , 10.46,  4.33,  3.43, 19.37, 17.21, 14.83,  9.95,
        5.95,  5.66,  7.25, 12.34, 15.15, 14.22,  7.76, 19.23, 15.54,
       12.42, 13.4 ,

In [128]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)


In [130]:

X_train.shape

(160, 1)

In [154]:
lr= MyLR()

In [158]:

lr.fit(X_train,y_train)

[-0.11543895]
[12.21155091]


In [160]:

X_train.shape[0]

160

In [162]:

X_train[0]

array([8.22])

In [164]:

X_train.mean()

6.8216875

In [168]:

X_test[0]

array([9.58])

In [170]:
print(lr.predict(X_test[0]))


[9.58]
[11.10564581]
